apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vouch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vouch.name" . }}
    helm.sh/chart: {{ include "vouch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vouch.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if (or .Values.deployment.annotations (not .Values.existingSecretName)) }}
      annotations:
      {{- else }}
      annotations: {}
      {{- end }}
      {{- with .Values.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.existingSecretName }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "vouch.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        secret:
          secretName: {{ if .Values.existingSecretName }}{{ .Values.existingSecretName }}{{- else }}{{ template "vouch.fullname" . }}{{- end }}
      - name: data
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
